version: '3.5'  

services:
    redis:
      image: redis
    backend: 
      image: backend 
      ports: 
        - 8000:8000
      environment:
        - 'FRONT_URL=http://localhost:5000'
        - 'REDIS=redis'
    frontend:
      image: frontend
      ports:
        - 5000:5000 
      environment:
        - 'API_URL=http://localhost:8000'