version: '3.5'  

services:
    redis:
      image: redis
    postgres:
      image: postgres
      environment:
        - POSTGRES_USER=joonauutela
        - POSTGRES_PASSWORD=password1
        - POSTGRES_DB=mydb 
    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
    backend: 
      image: backend 
      ports: 
        - 8000:8000
      environment:
        - FRONT_URL=http://192.168.99.100
        - REDIS=redis
        - DB_USERNAME=joonauutela
        - DB_PASSWORD=password1
        - DB_NAME=mydb
        - DB_HOST=postgres
    frontend:
      image: frontend
      ports:
        - 5000:5000 
      environment:
        - API_URL=http://192.168.99.100:8000